services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@vikrams.in
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - 8080:80

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379